name: Build and Release Money4Band

on:
  push:
    tags:
      - "*.*.*"  # Matches tags like 1.0.0, 2.1.1, etc.

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]  # Build for Linux, macOS, and Windows
        architecture: [x64, arm64, armv7]  # Target architectures
        exclude:
          - os: macos-latest
            architecture: armv7  # macOS doesn't support ARMv7
          - os: windows-latest
            architecture: armv7  # Windows doesn't support ARMv7

    steps:
      - name: Checkout the code
        uses: actions/checkout@v4

      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: 'pip'  # Enables caching for pip dependencies

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Build with PyInstaller
        run: |
          pyinstaller --onedir --name Money4Band main.py --hidden-import colorama --hidden-import docker --hidden-import requests --hidden-import pyyaml --hidden-import psutil --hidden-import yaml --hidden-import secrets --add-data ".resources:.resources" --add-data "config:config" --add-data "utils:utils" --add-data "legacy_money4bandv3x:legacy_money4bandv3x" --add-data "template:template" --add-data "LICENSE:LICENSE" --add-data "README.md:README.md" --contents-directory "." -y

      - name: Archive build artifacts for release
        run: |
          if [ "${{ matrix.os }}" == "windows-latest" ]; then
            zip -r Money4Band-${{ matrix.os }}-${{ matrix.architecture }}-${{ github.ref_name }}.zip dist/Money4Band;
          else
            tar -czvf Money4Band-${{ matrix.os }}-${{ matrix.architecture }}-${{ github.ref_name }}.tar.gz dist/Money4Band;
          fi

      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: Money4Band-${{ matrix.os }}-${{ matrix.architecture }}-${{ github.ref_name }}
          path: |
            Money4Band-${{ matrix.os }}-${{ matrix.architecture }}-${{ github.ref_name }}.zip
            Money4Band-${{ matrix.os }}-${{ matrix.architecture }}-${{ github.ref_name }}.tar.gz

  release:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout the code
        uses: actions/checkout@v4

      - name: Create a GitHub release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          name: Money4Band ${{ github.ref_name }}
          tag_name: ${{ github.ref_name }}
          files: |
            Money4Band-ubuntu-latest-x64-${{ github.ref_name }}.tar.gz
            Money4Band-ubuntu-latest-arm64-${{ github.ref_name }}.tar.gz
            Money4Band-ubuntu-latest-armv7-${{ github.ref_name }}.tar.gz
            Money4Band-macos-latest-x64-${{ github.ref_name }}.tar.gz
            Money4Band-macos-latest-arm64-${{ github.ref_name }}.tar.gz
            Money4Band-windows-latest-x64-${{ github.ref_name }}.zip
            Money4Band-windows-latest-arm64-${{ github.ref_name }}.zip
          body: |
            Release version ${{ github.ref_name }} of Money4Band
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
